export const SelectInputStyles: import("lit-html").TemplateResult<1>;
export const DropdownStyles: import("lit-html").TemplateResult<1>;
export const UnderlinedInputStyles: import("lit-html").TemplateResult<1>;
export const CheckboxStyles: import("lit-html").TemplateResult<1>;
export const PlainInputStyles: import("lit-html").TemplateResult<1>;
export const LargeInputStyles: import("lit-html").TemplateResult<1>;
export const BoxInputStyles: import("lit-html").TemplateResult<1>;
export const SmallInputStyles: import("lit-html").TemplateResult<1>;
export const AllInputStyles: import("lit-html").TemplateResult<1>;
